# Generated by Django 5.2.5 on 2025-08-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='Unknown Brand', max_length=50),
        ),
    ]
